<#import "parts/common.ftlh" as c>
<@c.page>
    <div style="position: absolute;
    top: 50%;
    left: 50%;
    margin-right: -50%;
    transform: translate(-50%, -50%);">
        <h1 style="text-align: center;">Welcome!</h1>
        <a href="/main" style="display: block;
    text-align: center;
    font-size: 25px;
    color: cornflowerblue;
    text-decoration: none;">
            Main page
        </a>
    </div>
</@c.page>